// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/cmd/devctl/internal/init (interfaces: manifestInitializer)
//
// Generated by this command:
//
//	mockgen -destination mocks/manifest.go -package mocks -typed . manifestInitializer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockmanifestInitializer is a mock of manifestInitializer interface.
type MockmanifestInitializer struct {
	ctrl     *gomock.Controller
	recorder *MockmanifestInitializerMockRecorder
	isgomock struct{}
}

// MockmanifestInitializerMockRecorder is the mock recorder for MockmanifestInitializer.
type MockmanifestInitializerMockRecorder struct {
	mock *MockmanifestInitializer
}

// NewMockmanifestInitializer creates a new mock instance.
func NewMockmanifestInitializer(ctrl *gomock.Controller) *MockmanifestInitializer {
	mock := &MockmanifestInitializer{ctrl: ctrl}
	mock.recorder = &MockmanifestInitializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmanifestInitializer) EXPECT() *MockmanifestInitializerMockRecorder {
	return m.recorder
}

// InitManifest mocks base method.
func (m *MockmanifestInitializer) InitManifest(ctx context.Context, command project.InitManifestCommand) (project.ManifestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitManifest", ctx, command)
	ret0, _ := ret[0].(project.ManifestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitManifest indicates an expected call of InitManifest.
func (mr *MockmanifestInitializerMockRecorder) InitManifest(ctx, command any) *MockmanifestInitializerInitManifestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitManifest", reflect.TypeOf((*MockmanifestInitializer)(nil).InitManifest), ctx, command)
	return &MockmanifestInitializerInitManifestCall{Call: call}
}

// MockmanifestInitializerInitManifestCall wrap *gomock.Call
type MockmanifestInitializerInitManifestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockmanifestInitializerInitManifestCall) Return(arg0 project.ManifestResult, arg1 error) *MockmanifestInitializerInitManifestCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockmanifestInitializerInitManifestCall) Do(f func(context.Context, project.InitManifestCommand) (project.ManifestResult, error)) *MockmanifestInitializerInitManifestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockmanifestInitializerInitManifestCall) DoAndReturn(f func(context.Context, project.InitManifestCommand) (project.ManifestResult, error)) *MockmanifestInitializerInitManifestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
