// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/cmd/devctl/internal/init (interfaces: scaffolder)
//
// Generated by this command:
//
//	mockgen -destination mocks/scaffold.go -package mocks -typed . scaffolder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	scaffold "github.com/devctllabs/devctl/internal/domain/scaffold"
	gomock "go.uber.org/mock/gomock"
)

// Mockscaffolder is a mock of scaffolder interface.
type Mockscaffolder struct {
	ctrl     *gomock.Controller
	recorder *MockscaffolderMockRecorder
	isgomock struct{}
}

// MockscaffolderMockRecorder is the mock recorder for Mockscaffolder.
type MockscaffolderMockRecorder struct {
	mock *Mockscaffolder
}

// NewMockscaffolder creates a new mock instance.
func NewMockscaffolder(ctrl *gomock.Controller) *Mockscaffolder {
	mock := &Mockscaffolder{ctrl: ctrl}
	mock.recorder = &MockscaffolderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockscaffolder) EXPECT() *MockscaffolderMockRecorder {
	return m.recorder
}

// Scaffold mocks base method.
func (m *Mockscaffolder) Scaffold(ctx context.Context, command scaffold.Command) (scaffold.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scaffold", ctx, command)
	ret0, _ := ret[0].(scaffold.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scaffold indicates an expected call of Scaffold.
func (mr *MockscaffolderMockRecorder) Scaffold(ctx, command any) *MockscaffolderScaffoldCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scaffold", reflect.TypeOf((*Mockscaffolder)(nil).Scaffold), ctx, command)
	return &MockscaffolderScaffoldCall{Call: call}
}

// MockscaffolderScaffoldCall wrap *gomock.Call
type MockscaffolderScaffoldCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockscaffolderScaffoldCall) Return(arg0 scaffold.Result, arg1 error) *MockscaffolderScaffoldCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockscaffolderScaffoldCall) Do(f func(context.Context, scaffold.Command) (scaffold.Result, error)) *MockscaffolderScaffoldCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockscaffolderScaffoldCall) DoAndReturn(f func(context.Context, scaffold.Command) (scaffold.Result, error)) *MockscaffolderScaffoldCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
