// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/cmd/devctl/internal/lint (interfaces: linter)
//
// Generated by this command:
//
//	mockgen -destination mocks/lint.go -package mocks -typed . linter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	lint "github.com/devctllabs/devctl/internal/domain/lint"
	gomock "go.uber.org/mock/gomock"
)

// Mocklinter is a mock of linter interface.
type Mocklinter struct {
	ctrl     *gomock.Controller
	recorder *MocklinterMockRecorder
	isgomock struct{}
}

// MocklinterMockRecorder is the mock recorder for Mocklinter.
type MocklinterMockRecorder struct {
	mock *Mocklinter
}

// NewMocklinter creates a new mock instance.
func NewMocklinter(ctrl *gomock.Controller) *Mocklinter {
	mock := &Mocklinter{ctrl: ctrl}
	mock.recorder = &MocklinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocklinter) EXPECT() *MocklinterMockRecorder {
	return m.recorder
}

// Lint mocks base method.
func (m *Mocklinter) Lint(ctx context.Context, command lint.Command) (lint.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lint", ctx, command)
	ret0, _ := ret[0].(lint.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lint indicates an expected call of Lint.
func (mr *MocklinterMockRecorder) Lint(ctx, command any) *MocklinterLintCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lint", reflect.TypeOf((*Mocklinter)(nil).Lint), ctx, command)
	return &MocklinterLintCall{Call: call}
}

// MocklinterLintCall wrap *gomock.Call
type MocklinterLintCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocklinterLintCall) Return(arg0 lint.Result, arg1 error) *MocklinterLintCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocklinterLintCall) Do(f func(context.Context, lint.Command) (lint.Result, error)) *MocklinterLintCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocklinterLintCall) DoAndReturn(f func(context.Context, lint.Command) (lint.Result, error)) *MocklinterLintCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
