// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/cmd/devctl/internal/validate (interfaces: projectValidator)
//
// Generated by this command:
//
//	mockgen -destination mocks/validate.go -package mocks -typed . projectValidator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockprojectValidator is a mock of projectValidator interface.
type MockprojectValidator struct {
	ctrl     *gomock.Controller
	recorder *MockprojectValidatorMockRecorder
	isgomock struct{}
}

// MockprojectValidatorMockRecorder is the mock recorder for MockprojectValidator.
type MockprojectValidatorMockRecorder struct {
	mock *MockprojectValidator
}

// NewMockprojectValidator creates a new mock instance.
func NewMockprojectValidator(ctrl *gomock.Controller) *MockprojectValidator {
	mock := &MockprojectValidator{ctrl: ctrl}
	mock.recorder = &MockprojectValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectValidator) EXPECT() *MockprojectValidatorMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockprojectValidator) Validate(ctx context.Context, query project.ValidateQuery) (project.ValidationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, query)
	ret0, _ := ret[0].(project.ValidationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockprojectValidatorMockRecorder) Validate(ctx, query any) *MockprojectValidatorValidateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockprojectValidator)(nil).Validate), ctx, query)
	return &MockprojectValidatorValidateCall{Call: call}
}

// MockprojectValidatorValidateCall wrap *gomock.Call
type MockprojectValidatorValidateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockprojectValidatorValidateCall) Return(arg0 project.ValidationResult, arg1 error) *MockprojectValidatorValidateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockprojectValidatorValidateCall) Do(f func(context.Context, project.ValidateQuery) (project.ValidationResult, error)) *MockprojectValidatorValidateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockprojectValidatorValidateCall) DoAndReturn(f func(context.Context, project.ValidateQuery) (project.ValidationResult, error)) *MockprojectValidatorValidateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
