// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/cmd/devctl/internal/inspect (interfaces: projectInspector)
//
// Generated by this command:
//
//	mockgen -destination mocks/inspect.go -package mocks -typed . projectInspector
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockprojectInspector is a mock of projectInspector interface.
type MockprojectInspector struct {
	ctrl     *gomock.Controller
	recorder *MockprojectInspectorMockRecorder
	isgomock struct{}
}

// MockprojectInspectorMockRecorder is the mock recorder for MockprojectInspector.
type MockprojectInspectorMockRecorder struct {
	mock *MockprojectInspector
}

// NewMockprojectInspector creates a new mock instance.
func NewMockprojectInspector(ctrl *gomock.Controller) *MockprojectInspector {
	mock := &MockprojectInspector{ctrl: ctrl}
	mock.recorder = &MockprojectInspectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectInspector) EXPECT() *MockprojectInspectorMockRecorder {
	return m.recorder
}

// Inspect mocks base method.
func (m *MockprojectInspector) Inspect(ctx context.Context, query project.InspectQuery) (project.InspectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", ctx, query)
	ret0, _ := ret[0].(project.InspectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockprojectInspectorMockRecorder) Inspect(ctx, query any) *MockprojectInspectorInspectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockprojectInspector)(nil).Inspect), ctx, query)
	return &MockprojectInspectorInspectCall{Call: call}
}

// MockprojectInspectorInspectCall wrap *gomock.Call
type MockprojectInspectorInspectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockprojectInspectorInspectCall) Return(arg0 project.InspectResult, arg1 error) *MockprojectInspectorInspectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockprojectInspectorInspectCall) Do(f func(context.Context, project.InspectQuery) (project.InspectResult, error)) *MockprojectInspectorInspectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockprojectInspectorInspectCall) DoAndReturn(f func(context.Context, project.InspectQuery) (project.InspectResult, error)) *MockprojectInspectorInspectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
