// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/internal/service/scaffold (interfaces: ProjectRepository,WorkspaceRepository)
//
// Generated by this command:
//
//	mockgen -destination mocks/ports.go -package mocks -typed . ProjectRepository,WorkspaceRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	fs "io/fs"
	reflect "reflect"

	artifact "github.com/devctllabs/devctl/internal/domain/artifact"
	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// LoadProject mocks base method.
func (m *MockProjectRepository) LoadProject(ctx context.Context, manifestPath string) (project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadProject", ctx, manifestPath)
	ret0, _ := ret[0].(project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadProject indicates an expected call of LoadProject.
func (mr *MockProjectRepositoryMockRecorder) LoadProject(ctx, manifestPath any) *MockProjectRepositoryLoadProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadProject", reflect.TypeOf((*MockProjectRepository)(nil).LoadProject), ctx, manifestPath)
	return &MockProjectRepositoryLoadProjectCall{Call: call}
}

// MockProjectRepositoryLoadProjectCall wrap *gomock.Call
type MockProjectRepositoryLoadProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectRepositoryLoadProjectCall) Return(arg0 project.Project, arg1 error) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectRepositoryLoadProjectCall) Do(f func(context.Context, string) (project.Project, error)) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectRepositoryLoadProjectCall) DoAndReturn(f func(context.Context, string) (project.Project, error)) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockWorkspaceRepository is a mock of WorkspaceRepository interface.
type MockWorkspaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkspaceRepositoryMockRecorder is the mock recorder for MockWorkspaceRepository.
type MockWorkspaceRepositoryMockRecorder struct {
	mock *MockWorkspaceRepository
}

// NewMockWorkspaceRepository creates a new mock instance.
func NewMockWorkspaceRepository(ctrl *gomock.Controller) *MockWorkspaceRepository {
	mock := &MockWorkspaceRepository{ctrl: ctrl}
	mock.recorder = &MockWorkspaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceRepository) EXPECT() *MockWorkspaceRepositoryMockRecorder {
	return m.recorder
}

// Lstat mocks base method.
func (m *MockWorkspaceRepository) Lstat(ctx context.Context, root, name string) (fs.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lstat", ctx, root, name)
	ret0, _ := ret[0].(fs.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lstat indicates an expected call of Lstat.
func (mr *MockWorkspaceRepositoryMockRecorder) Lstat(ctx, root, name any) *MockWorkspaceRepositoryLstatCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lstat", reflect.TypeOf((*MockWorkspaceRepository)(nil).Lstat), ctx, root, name)
	return &MockWorkspaceRepositoryLstatCall{Call: call}
}

// MockWorkspaceRepositoryLstatCall wrap *gomock.Call
type MockWorkspaceRepositoryLstatCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRepositoryLstatCall) Return(arg0 fs.FileInfo, arg1 error) *MockWorkspaceRepositoryLstatCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRepositoryLstatCall) Do(f func(context.Context, string, string) (fs.FileInfo, error)) *MockWorkspaceRepositoryLstatCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRepositoryLstatCall) DoAndReturn(f func(context.Context, string, string) (fs.FileInfo, error)) *MockWorkspaceRepositoryLstatCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PublishFile mocks base method.
func (m *MockWorkspaceRepository) PublishFile(ctx context.Context, root, target string, content []byte) (artifact.PublishResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFile", ctx, root, target, content)
	ret0, _ := ret[0].(artifact.PublishResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishFile indicates an expected call of PublishFile.
func (mr *MockWorkspaceRepositoryMockRecorder) PublishFile(ctx, root, target, content any) *MockWorkspaceRepositoryPublishFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFile", reflect.TypeOf((*MockWorkspaceRepository)(nil).PublishFile), ctx, root, target, content)
	return &MockWorkspaceRepositoryPublishFileCall{Call: call}
}

// MockWorkspaceRepositoryPublishFileCall wrap *gomock.Call
type MockWorkspaceRepositoryPublishFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRepositoryPublishFileCall) Return(arg0 artifact.PublishResult, arg1 error) *MockWorkspaceRepositoryPublishFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRepositoryPublishFileCall) Do(f func(context.Context, string, string, []byte) (artifact.PublishResult, error)) *MockWorkspaceRepositoryPublishFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRepositoryPublishFileCall) DoAndReturn(f func(context.Context, string, string, []byte) (artifact.PublishResult, error)) *MockWorkspaceRepositoryPublishFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadBytes mocks base method.
func (m *MockWorkspaceRepository) ReadBytes(ctx context.Context, root, name string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBytes", ctx, root, name)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBytes indicates an expected call of ReadBytes.
func (mr *MockWorkspaceRepositoryMockRecorder) ReadBytes(ctx, root, name any) *MockWorkspaceRepositoryReadBytesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBytes", reflect.TypeOf((*MockWorkspaceRepository)(nil).ReadBytes), ctx, root, name)
	return &MockWorkspaceRepositoryReadBytesCall{Call: call}
}

// MockWorkspaceRepositoryReadBytesCall wrap *gomock.Call
type MockWorkspaceRepositoryReadBytesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRepositoryReadBytesCall) Return(arg0 []byte, arg1 error) *MockWorkspaceRepositoryReadBytesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRepositoryReadBytesCall) Do(f func(context.Context, string, string) ([]byte, error)) *MockWorkspaceRepositoryReadBytesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRepositoryReadBytesCall) DoAndReturn(f func(context.Context, string, string) ([]byte, error)) *MockWorkspaceRepositoryReadBytesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Walk mocks base method.
func (m *MockWorkspaceRepository) Walk(ctx context.Context, root string, visit fs.WalkDirFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Walk", ctx, root, visit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Walk indicates an expected call of Walk.
func (mr *MockWorkspaceRepositoryMockRecorder) Walk(ctx, root, visit any) *MockWorkspaceRepositoryWalkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Walk", reflect.TypeOf((*MockWorkspaceRepository)(nil).Walk), ctx, root, visit)
	return &MockWorkspaceRepositoryWalkCall{Call: call}
}

// MockWorkspaceRepositoryWalkCall wrap *gomock.Call
type MockWorkspaceRepositoryWalkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRepositoryWalkCall) Return(arg0 error) *MockWorkspaceRepositoryWalkCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRepositoryWalkCall) Do(f func(context.Context, string, fs.WalkDirFunc) error) *MockWorkspaceRepositoryWalkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRepositoryWalkCall) DoAndReturn(f func(context.Context, string, fs.WalkDirFunc) error) *MockWorkspaceRepositoryWalkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
