// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/cmd/devctl/internal/enable (interfaces: capabilityEnabler)
//
// Generated by this command:
//
//	mockgen -destination mocks/capability.go -package mocks -typed . capabilityEnabler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockcapabilityEnabler is a mock of capabilityEnabler interface.
type MockcapabilityEnabler struct {
	ctrl     *gomock.Controller
	recorder *MockcapabilityEnablerMockRecorder
	isgomock struct{}
}

// MockcapabilityEnablerMockRecorder is the mock recorder for MockcapabilityEnabler.
type MockcapabilityEnablerMockRecorder struct {
	mock *MockcapabilityEnabler
}

// NewMockcapabilityEnabler creates a new mock instance.
func NewMockcapabilityEnabler(ctrl *gomock.Controller) *MockcapabilityEnabler {
	mock := &MockcapabilityEnabler{ctrl: ctrl}
	mock.recorder = &MockcapabilityEnablerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcapabilityEnabler) EXPECT() *MockcapabilityEnablerMockRecorder {
	return m.recorder
}

// Enable mocks base method.
func (m *MockcapabilityEnabler) Enable(ctx context.Context, command project.EnableCommand) (project.ManifestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", ctx, command)
	ret0, _ := ret[0].(project.ManifestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enable indicates an expected call of Enable.
func (mr *MockcapabilityEnablerMockRecorder) Enable(ctx, command any) *MockcapabilityEnablerEnableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockcapabilityEnabler)(nil).Enable), ctx, command)
	return &MockcapabilityEnablerEnableCall{Call: call}
}

// MockcapabilityEnablerEnableCall wrap *gomock.Call
type MockcapabilityEnablerEnableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockcapabilityEnablerEnableCall) Return(arg0 project.ManifestResult, arg1 error) *MockcapabilityEnablerEnableCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockcapabilityEnablerEnableCall) Do(f func(context.Context, project.EnableCommand) (project.ManifestResult, error)) *MockcapabilityEnablerEnableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockcapabilityEnablerEnableCall) DoAndReturn(f func(context.Context, project.EnableCommand) (project.ManifestResult, error)) *MockcapabilityEnablerEnableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
