// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/internal/service/generate (interfaces: ProjectRepository,TargetResolver,GeneratorClient,WorkspaceRepository)
//
// Generated by this command:
//
//	mockgen -destination mocks/service.go -package mocks -typed . ProjectRepository,TargetResolver,GeneratorClient,WorkspaceRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	artifact "github.com/devctllabs/devctl/internal/domain/artifact"
	generate "github.com/devctllabs/devctl/internal/domain/generate"
	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// LoadProject mocks base method.
func (m *MockProjectRepository) LoadProject(ctx context.Context, manifestPath string) (project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadProject", ctx, manifestPath)
	ret0, _ := ret[0].(project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadProject indicates an expected call of LoadProject.
func (mr *MockProjectRepositoryMockRecorder) LoadProject(ctx, manifestPath any) *MockProjectRepositoryLoadProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadProject", reflect.TypeOf((*MockProjectRepository)(nil).LoadProject), ctx, manifestPath)
	return &MockProjectRepositoryLoadProjectCall{Call: call}
}

// MockProjectRepositoryLoadProjectCall wrap *gomock.Call
type MockProjectRepositoryLoadProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectRepositoryLoadProjectCall) Return(arg0 project.Project, arg1 error) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectRepositoryLoadProjectCall) Do(f func(context.Context, string) (project.Project, error)) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectRepositoryLoadProjectCall) DoAndReturn(f func(context.Context, string) (project.Project, error)) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTargetResolver is a mock of TargetResolver interface.
type MockTargetResolver struct {
	ctrl     *gomock.Controller
	recorder *MockTargetResolverMockRecorder
	isgomock struct{}
}

// MockTargetResolverMockRecorder is the mock recorder for MockTargetResolver.
type MockTargetResolverMockRecorder struct {
	mock *MockTargetResolver
}

// NewMockTargetResolver creates a new mock instance.
func NewMockTargetResolver(ctrl *gomock.Controller) *MockTargetResolver {
	mock := &MockTargetResolver{ctrl: ctrl}
	mock.recorder = &MockTargetResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetResolver) EXPECT() *MockTargetResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockTargetResolver) Resolve(ctx context.Context, selected project.Project, target project.Target) (project.Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, selected, target)
	ret0, _ := ret[0].(project.Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockTargetResolverMockRecorder) Resolve(ctx, selected, target any) *MockTargetResolverResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockTargetResolver)(nil).Resolve), ctx, selected, target)
	return &MockTargetResolverResolveCall{Call: call}
}

// MockTargetResolverResolveCall wrap *gomock.Call
type MockTargetResolverResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTargetResolverResolveCall) Return(arg0 project.Target, arg1 error) *MockTargetResolverResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTargetResolverResolveCall) Do(f func(context.Context, project.Project, project.Target) (project.Target, error)) *MockTargetResolverResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTargetResolverResolveCall) DoAndReturn(f func(context.Context, project.Project, project.Target) (project.Target, error)) *MockTargetResolverResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockGeneratorClient is a mock of GeneratorClient interface.
type MockGeneratorClient struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorClientMockRecorder
	isgomock struct{}
}

// MockGeneratorClientMockRecorder is the mock recorder for MockGeneratorClient.
type MockGeneratorClientMockRecorder struct {
	mock *MockGeneratorClient
}

// NewMockGeneratorClient creates a new mock instance.
func NewMockGeneratorClient(ctrl *gomock.Controller) *MockGeneratorClient {
	mock := &MockGeneratorClient{ctrl: ctrl}
	mock.recorder = &MockGeneratorClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeneratorClient) EXPECT() *MockGeneratorClientMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockGeneratorClient) Generate(ctx context.Context, arg1 project.Project, target project.Target) (generate.Output, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, arg1, target)
	ret0, _ := ret[0].(generate.Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockGeneratorClientMockRecorder) Generate(ctx, arg1, target any) *MockGeneratorClientGenerateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockGeneratorClient)(nil).Generate), ctx, arg1, target)
	return &MockGeneratorClientGenerateCall{Call: call}
}

// MockGeneratorClientGenerateCall wrap *gomock.Call
type MockGeneratorClientGenerateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGeneratorClientGenerateCall) Return(arg0 generate.Output, arg1 error) *MockGeneratorClientGenerateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGeneratorClientGenerateCall) Do(f func(context.Context, project.Project, project.Target) (generate.Output, error)) *MockGeneratorClientGenerateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGeneratorClientGenerateCall) DoAndReturn(f func(context.Context, project.Project, project.Target) (generate.Output, error)) *MockGeneratorClientGenerateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockWorkspaceRepository is a mock of WorkspaceRepository interface.
type MockWorkspaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkspaceRepositoryMockRecorder is the mock recorder for MockWorkspaceRepository.
type MockWorkspaceRepositoryMockRecorder struct {
	mock *MockWorkspaceRepository
}

// NewMockWorkspaceRepository creates a new mock instance.
func NewMockWorkspaceRepository(ctrl *gomock.Controller) *MockWorkspaceRepository {
	mock := &MockWorkspaceRepository{ctrl: ctrl}
	mock.recorder = &MockWorkspaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceRepository) EXPECT() *MockWorkspaceRepositoryMockRecorder {
	return m.recorder
}

// PublishDirectory mocks base method.
func (m *MockWorkspaceRepository) PublishDirectory(ctx context.Context, root, target string, tree artifact.Tree) (artifact.PublishResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDirectory", ctx, root, target, tree)
	ret0, _ := ret[0].(artifact.PublishResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishDirectory indicates an expected call of PublishDirectory.
func (mr *MockWorkspaceRepositoryMockRecorder) PublishDirectory(ctx, root, target, tree any) *MockWorkspaceRepositoryPublishDirectoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDirectory", reflect.TypeOf((*MockWorkspaceRepository)(nil).PublishDirectory), ctx, root, target, tree)
	return &MockWorkspaceRepositoryPublishDirectoryCall{Call: call}
}

// MockWorkspaceRepositoryPublishDirectoryCall wrap *gomock.Call
type MockWorkspaceRepositoryPublishDirectoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRepositoryPublishDirectoryCall) Return(arg0 artifact.PublishResult, arg1 error) *MockWorkspaceRepositoryPublishDirectoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRepositoryPublishDirectoryCall) Do(f func(context.Context, string, string, artifact.Tree) (artifact.PublishResult, error)) *MockWorkspaceRepositoryPublishDirectoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRepositoryPublishDirectoryCall) DoAndReturn(f func(context.Context, string, string, artifact.Tree) (artifact.PublishResult, error)) *MockWorkspaceRepositoryPublishDirectoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PublishFile mocks base method.
func (m *MockWorkspaceRepository) PublishFile(ctx context.Context, root, target string, content []byte) (artifact.PublishResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFile", ctx, root, target, content)
	ret0, _ := ret[0].(artifact.PublishResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishFile indicates an expected call of PublishFile.
func (mr *MockWorkspaceRepositoryMockRecorder) PublishFile(ctx, root, target, content any) *MockWorkspaceRepositoryPublishFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFile", reflect.TypeOf((*MockWorkspaceRepository)(nil).PublishFile), ctx, root, target, content)
	return &MockWorkspaceRepositoryPublishFileCall{Call: call}
}

// MockWorkspaceRepositoryPublishFileCall wrap *gomock.Call
type MockWorkspaceRepositoryPublishFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRepositoryPublishFileCall) Return(arg0 artifact.PublishResult, arg1 error) *MockWorkspaceRepositoryPublishFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRepositoryPublishFileCall) Do(f func(context.Context, string, string, []byte) (artifact.PublishResult, error)) *MockWorkspaceRepositoryPublishFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRepositoryPublishFileCall) DoAndReturn(f func(context.Context, string, string, []byte) (artifact.PublishResult, error)) *MockWorkspaceRepositoryPublishFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
