// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/internal/service/materialize (interfaces: FileReader,HTTPClient,GitClient,ManifestRepository)
//
// Generated by this command:
//
//	mockgen -destination mocks/ports.go -package mocks -typed . FileReader,HTTPClient,GitClient,ManifestRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	contract "github.com/devctllabs/devctl/internal/domain/contract"
	materialize "github.com/devctllabs/devctl/internal/domain/materialize"
	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockFileReader is a mock of FileReader interface.
type MockFileReader struct {
	ctrl     *gomock.Controller
	recorder *MockFileReaderMockRecorder
	isgomock struct{}
}

// MockFileReaderMockRecorder is the mock recorder for MockFileReader.
type MockFileReaderMockRecorder struct {
	mock *MockFileReader
}

// NewMockFileReader creates a new mock instance.
func NewMockFileReader(ctrl *gomock.Controller) *MockFileReader {
	mock := &MockFileReader{ctrl: ctrl}
	mock.recorder = &MockFileReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileReader) EXPECT() *MockFileReaderMockRecorder {
	return m.recorder
}

// ReadFile mocks base method.
func (m *MockFileReader) ReadFile(ctx context.Context, root, name string) (contract.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, root, name)
	ret0, _ := ret[0].(contract.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockFileReaderMockRecorder) ReadFile(ctx, root, name any) *MockFileReaderReadFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockFileReader)(nil).ReadFile), ctx, root, name)
	return &MockFileReaderReadFileCall{Call: call}
}

// MockFileReaderReadFileCall wrap *gomock.Call
type MockFileReaderReadFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileReaderReadFileCall) Return(arg0 contract.File, arg1 error) *MockFileReaderReadFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileReaderReadFileCall) Do(f func(context.Context, string, string) (contract.File, error)) *MockFileReaderReadFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileReaderReadFileCall) DoAndReturn(f func(context.Context, string, string) (contract.File, error)) *MockFileReaderReadFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadTree mocks base method.
func (m *MockFileReader) ReadTree(ctx context.Context, root, directory string) ([]contract.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadTree", ctx, root, directory)
	ret0, _ := ret[0].([]contract.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadTree indicates an expected call of ReadTree.
func (mr *MockFileReaderMockRecorder) ReadTree(ctx, root, directory any) *MockFileReaderReadTreeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTree", reflect.TypeOf((*MockFileReader)(nil).ReadTree), ctx, root, directory)
	return &MockFileReaderReadTreeCall{Call: call}
}

// MockFileReaderReadTreeCall wrap *gomock.Call
type MockFileReaderReadTreeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockFileReaderReadTreeCall) Return(arg0 []contract.File, arg1 error) *MockFileReaderReadTreeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockFileReaderReadTreeCall) Do(f func(context.Context, string, string) ([]contract.File, error)) *MockFileReaderReadTreeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockFileReaderReadTreeCall) DoAndReturn(f func(context.Context, string, string) ([]contract.File, error)) *MockFileReaderReadTreeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockHTTPClient) Fetch(ctx context.Context, request materialize.HTTPFetchRequest) (materialize.HTTPDocument, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, request)
	ret0, _ := ret[0].(materialize.HTTPDocument)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockHTTPClientMockRecorder) Fetch(ctx, request any) *MockHTTPClientFetchCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockHTTPClient)(nil).Fetch), ctx, request)
	return &MockHTTPClientFetchCall{Call: call}
}

// MockHTTPClientFetchCall wrap *gomock.Call
type MockHTTPClientFetchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHTTPClientFetchCall) Return(arg0 materialize.HTTPDocument, arg1 error) *MockHTTPClientFetchCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHTTPClientFetchCall) Do(f func(context.Context, materialize.HTTPFetchRequest) (materialize.HTTPDocument, error)) *MockHTTPClientFetchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHTTPClientFetchCall) DoAndReturn(f func(context.Context, materialize.HTTPFetchRequest) (materialize.HTTPDocument, error)) *MockHTTPClientFetchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockGitClient is a mock of GitClient interface.
type MockGitClient struct {
	ctrl     *gomock.Controller
	recorder *MockGitClientMockRecorder
	isgomock struct{}
}

// MockGitClientMockRecorder is the mock recorder for MockGitClient.
type MockGitClientMockRecorder struct {
	mock *MockGitClient
}

// NewMockGitClient creates a new mock instance.
func NewMockGitClient(ctrl *gomock.Controller) *MockGitClient {
	mock := &MockGitClient{ctrl: ctrl}
	mock.recorder = &MockGitClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitClient) EXPECT() *MockGitClientMockRecorder {
	return m.recorder
}

// WithCheckout mocks base method.
func (m *MockGitClient) WithCheckout(ctx context.Context, repository, ref string, use func(string) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCheckout", ctx, repository, ref, use)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithCheckout indicates an expected call of WithCheckout.
func (mr *MockGitClientMockRecorder) WithCheckout(ctx, repository, ref, use any) *MockGitClientWithCheckoutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCheckout", reflect.TypeOf((*MockGitClient)(nil).WithCheckout), ctx, repository, ref, use)
	return &MockGitClientWithCheckoutCall{Call: call}
}

// MockGitClientWithCheckoutCall wrap *gomock.Call
type MockGitClientWithCheckoutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGitClientWithCheckoutCall) Return(arg0 error) *MockGitClientWithCheckoutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGitClientWithCheckoutCall) Do(f func(context.Context, string, string, func(string) error) error) *MockGitClientWithCheckoutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGitClientWithCheckoutCall) DoAndReturn(f func(context.Context, string, string, func(string) error) error) *MockGitClientWithCheckoutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockManifestRepository is a mock of ManifestRepository interface.
type MockManifestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockManifestRepositoryMockRecorder
	isgomock struct{}
}

// MockManifestRepositoryMockRecorder is the mock recorder for MockManifestRepository.
type MockManifestRepositoryMockRecorder struct {
	mock *MockManifestRepository
}

// NewMockManifestRepository creates a new mock instance.
func NewMockManifestRepository(ctrl *gomock.Controller) *MockManifestRepository {
	mock := &MockManifestRepository{ctrl: ctrl}
	mock.recorder = &MockManifestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManifestRepository) EXPECT() *MockManifestRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockManifestRepository) Load(ctx context.Context, manifestPath string) (project.LoadManifestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, manifestPath)
	ret0, _ := ret[0].(project.LoadManifestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockManifestRepositoryMockRecorder) Load(ctx, manifestPath any) *MockManifestRepositoryLoadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockManifestRepository)(nil).Load), ctx, manifestPath)
	return &MockManifestRepositoryLoadCall{Call: call}
}

// MockManifestRepositoryLoadCall wrap *gomock.Call
type MockManifestRepositoryLoadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestRepositoryLoadCall) Return(arg0 project.LoadManifestResult, arg1 error) *MockManifestRepositoryLoadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestRepositoryLoadCall) Do(f func(context.Context, string) (project.LoadManifestResult, error)) *MockManifestRepositoryLoadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestRepositoryLoadCall) DoAndReturn(f func(context.Context, string) (project.LoadManifestResult, error)) *MockManifestRepositoryLoadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
