// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/cmd/devctl/internal/add (interfaces: databaseAdder)
//
// Generated by this command:
//
//	mockgen -destination mocks/db.go -package mocks -typed . databaseAdder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockdatabaseAdder is a mock of databaseAdder interface.
type MockdatabaseAdder struct {
	ctrl     *gomock.Controller
	recorder *MockdatabaseAdderMockRecorder
	isgomock struct{}
}

// MockdatabaseAdderMockRecorder is the mock recorder for MockdatabaseAdder.
type MockdatabaseAdderMockRecorder struct {
	mock *MockdatabaseAdder
}

// NewMockdatabaseAdder creates a new mock instance.
func NewMockdatabaseAdder(ctrl *gomock.Controller) *MockdatabaseAdder {
	mock := &MockdatabaseAdder{ctrl: ctrl}
	mock.recorder = &MockdatabaseAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdatabaseAdder) EXPECT() *MockdatabaseAdderMockRecorder {
	return m.recorder
}

// AddDB mocks base method.
func (m *MockdatabaseAdder) AddDB(ctx context.Context, command project.AddDBCommand) (project.ManifestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDB", ctx, command)
	ret0, _ := ret[0].(project.ManifestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDB indicates an expected call of AddDB.
func (mr *MockdatabaseAdderMockRecorder) AddDB(ctx, command any) *MockdatabaseAdderAddDBCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDB", reflect.TypeOf((*MockdatabaseAdder)(nil).AddDB), ctx, command)
	return &MockdatabaseAdderAddDBCall{Call: call}
}

// MockdatabaseAdderAddDBCall wrap *gomock.Call
type MockdatabaseAdderAddDBCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockdatabaseAdderAddDBCall) Return(arg0 project.ManifestResult, arg1 error) *MockdatabaseAdderAddDBCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockdatabaseAdderAddDBCall) Do(f func(context.Context, project.AddDBCommand) (project.ManifestResult, error)) *MockdatabaseAdderAddDBCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockdatabaseAdderAddDBCall) DoAndReturn(f func(context.Context, project.AddDBCommand) (project.ManifestResult, error)) *MockdatabaseAdderAddDBCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
