// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/cmd/devctl/internal/add (interfaces: httpClientAdder)
//
// Generated by this command:
//
//	mockgen -destination mocks/http_client.go -package mocks -typed . httpClientAdder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockhttpClientAdder is a mock of httpClientAdder interface.
type MockhttpClientAdder struct {
	ctrl     *gomock.Controller
	recorder *MockhttpClientAdderMockRecorder
	isgomock struct{}
}

// MockhttpClientAdderMockRecorder is the mock recorder for MockhttpClientAdder.
type MockhttpClientAdderMockRecorder struct {
	mock *MockhttpClientAdder
}

// NewMockhttpClientAdder creates a new mock instance.
func NewMockhttpClientAdder(ctrl *gomock.Controller) *MockhttpClientAdder {
	mock := &MockhttpClientAdder{ctrl: ctrl}
	mock.recorder = &MockhttpClientAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhttpClientAdder) EXPECT() *MockhttpClientAdderMockRecorder {
	return m.recorder
}

// AddHTTPClient mocks base method.
func (m *MockhttpClientAdder) AddHTTPClient(ctx context.Context, command project.AddHTTPClientCommand) (project.ManifestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHTTPClient", ctx, command)
	ret0, _ := ret[0].(project.ManifestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddHTTPClient indicates an expected call of AddHTTPClient.
func (mr *MockhttpClientAdderMockRecorder) AddHTTPClient(ctx, command any) *MockhttpClientAdderAddHTTPClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHTTPClient", reflect.TypeOf((*MockhttpClientAdder)(nil).AddHTTPClient), ctx, command)
	return &MockhttpClientAdderAddHTTPClientCall{Call: call}
}

// MockhttpClientAdderAddHTTPClientCall wrap *gomock.Call
type MockhttpClientAdderAddHTTPClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockhttpClientAdderAddHTTPClientCall) Return(arg0 project.ManifestResult, arg1 error) *MockhttpClientAdderAddHTTPClientCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockhttpClientAdderAddHTTPClientCall) Do(f func(context.Context, project.AddHTTPClientCommand) (project.ManifestResult, error)) *MockhttpClientAdderAddHTTPClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockhttpClientAdderAddHTTPClientCall) DoAndReturn(f func(context.Context, project.AddHTTPClientCommand) (project.ManifestResult, error)) *MockhttpClientAdderAddHTTPClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
