// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/cmd/devctl/internal/add (interfaces: sourceAdder)
//
// Generated by this command:
//
//	mockgen -destination mocks/source.go -package mocks -typed . sourceAdder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MocksourceAdder is a mock of sourceAdder interface.
type MocksourceAdder struct {
	ctrl     *gomock.Controller
	recorder *MocksourceAdderMockRecorder
	isgomock struct{}
}

// MocksourceAdderMockRecorder is the mock recorder for MocksourceAdder.
type MocksourceAdderMockRecorder struct {
	mock *MocksourceAdder
}

// NewMocksourceAdder creates a new mock instance.
func NewMocksourceAdder(ctrl *gomock.Controller) *MocksourceAdder {
	mock := &MocksourceAdder{ctrl: ctrl}
	mock.recorder = &MocksourceAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksourceAdder) EXPECT() *MocksourceAdderMockRecorder {
	return m.recorder
}

// AddSource mocks base method.
func (m *MocksourceAdder) AddSource(ctx context.Context, command project.AddSourceCommand) (project.ManifestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSource", ctx, command)
	ret0, _ := ret[0].(project.ManifestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSource indicates an expected call of AddSource.
func (mr *MocksourceAdderMockRecorder) AddSource(ctx, command any) *MocksourceAdderAddSourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSource", reflect.TypeOf((*MocksourceAdder)(nil).AddSource), ctx, command)
	return &MocksourceAdderAddSourceCall{Call: call}
}

// MocksourceAdderAddSourceCall wrap *gomock.Call
type MocksourceAdderAddSourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksourceAdderAddSourceCall) Return(arg0 project.ManifestResult, arg1 error) *MocksourceAdderAddSourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksourceAdderAddSourceCall) Do(f func(context.Context, project.AddSourceCommand) (project.ManifestResult, error)) *MocksourceAdderAddSourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksourceAdderAddSourceCall) DoAndReturn(f func(context.Context, project.AddSourceCommand) (project.ManifestResult, error)) *MocksourceAdderAddSourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
