// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/internal/service/lint (interfaces: ProjectRepository,ContractLocator,TargetResolver,ProtoLinter)
//
// Generated by this command:
//
//	mockgen -destination mocks/service.go -package mocks -typed . ProjectRepository,ContractLocator,TargetResolver,ProtoLinter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	contract "github.com/devctllabs/devctl/internal/domain/contract"
	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// LoadProject mocks base method.
func (m *MockProjectRepository) LoadProject(ctx context.Context, manifestPath string) (project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadProject", ctx, manifestPath)
	ret0, _ := ret[0].(project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadProject indicates an expected call of LoadProject.
func (mr *MockProjectRepositoryMockRecorder) LoadProject(ctx, manifestPath any) *MockProjectRepositoryLoadProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadProject", reflect.TypeOf((*MockProjectRepository)(nil).LoadProject), ctx, manifestPath)
	return &MockProjectRepositoryLoadProjectCall{Call: call}
}

// MockProjectRepositoryLoadProjectCall wrap *gomock.Call
type MockProjectRepositoryLoadProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectRepositoryLoadProjectCall) Return(arg0 project.Project, arg1 error) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectRepositoryLoadProjectCall) Do(f func(context.Context, string) (project.Project, error)) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectRepositoryLoadProjectCall) DoAndReturn(f func(context.Context, string) (project.Project, error)) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockContractLocator is a mock of ContractLocator interface.
type MockContractLocator struct {
	ctrl     *gomock.Controller
	recorder *MockContractLocatorMockRecorder
	isgomock struct{}
}

// MockContractLocatorMockRecorder is the mock recorder for MockContractLocator.
type MockContractLocatorMockRecorder struct {
	mock *MockContractLocator
}

// NewMockContractLocator creates a new mock instance.
func NewMockContractLocator(ctrl *gomock.Controller) *MockContractLocator {
	mock := &MockContractLocator{ctrl: ctrl}
	mock.recorder = &MockContractLocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractLocator) EXPECT() *MockContractLocatorMockRecorder {
	return m.recorder
}

// ListProtoFiles mocks base method.
func (m *MockContractLocator) ListProtoFiles(ctx context.Context, root, relativeRoot string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProtoFiles", ctx, root, relativeRoot)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProtoFiles indicates an expected call of ListProtoFiles.
func (mr *MockContractLocatorMockRecorder) ListProtoFiles(ctx, root, relativeRoot any) *MockContractLocatorListProtoFilesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProtoFiles", reflect.TypeOf((*MockContractLocator)(nil).ListProtoFiles), ctx, root, relativeRoot)
	return &MockContractLocatorListProtoFilesCall{Call: call}
}

// MockContractLocatorListProtoFilesCall wrap *gomock.Call
type MockContractLocatorListProtoFilesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContractLocatorListProtoFilesCall) Return(arg0 []string, arg1 error) *MockContractLocatorListProtoFilesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContractLocatorListProtoFilesCall) Do(f func(context.Context, string, string) ([]string, error)) *MockContractLocatorListProtoFilesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContractLocatorListProtoFilesCall) DoAndReturn(f func(context.Context, string, string) ([]string, error)) *MockContractLocatorListProtoFilesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadContract mocks base method.
func (m *MockContractLocator) ReadContract(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadContract", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadContract indicates an expected call of ReadContract.
func (mr *MockContractLocatorMockRecorder) ReadContract(ctx, path any) *MockContractLocatorReadContractCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadContract", reflect.TypeOf((*MockContractLocator)(nil).ReadContract), ctx, path)
	return &MockContractLocatorReadContractCall{Call: call}
}

// MockContractLocatorReadContractCall wrap *gomock.Call
type MockContractLocatorReadContractCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContractLocatorReadContractCall) Return(arg0 []byte, arg1 error) *MockContractLocatorReadContractCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContractLocatorReadContractCall) Do(f func(context.Context, string) ([]byte, error)) *MockContractLocatorReadContractCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContractLocatorReadContractCall) DoAndReturn(f func(context.Context, string) ([]byte, error)) *MockContractLocatorReadContractCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolveContract mocks base method.
func (m *MockContractLocator) ResolveContract(ctx context.Context, location contract.Location) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveContract", ctx, location)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveContract indicates an expected call of ResolveContract.
func (mr *MockContractLocatorMockRecorder) ResolveContract(ctx, location any) *MockContractLocatorResolveContractCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveContract", reflect.TypeOf((*MockContractLocator)(nil).ResolveContract), ctx, location)
	return &MockContractLocatorResolveContractCall{Call: call}
}

// MockContractLocatorResolveContractCall wrap *gomock.Call
type MockContractLocatorResolveContractCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockContractLocatorResolveContractCall) Return(arg0 string, arg1 error) *MockContractLocatorResolveContractCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockContractLocatorResolveContractCall) Do(f func(context.Context, contract.Location) (string, error)) *MockContractLocatorResolveContractCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockContractLocatorResolveContractCall) DoAndReturn(f func(context.Context, contract.Location) (string, error)) *MockContractLocatorResolveContractCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTargetResolver is a mock of TargetResolver interface.
type MockTargetResolver struct {
	ctrl     *gomock.Controller
	recorder *MockTargetResolverMockRecorder
	isgomock struct{}
}

// MockTargetResolverMockRecorder is the mock recorder for MockTargetResolver.
type MockTargetResolverMockRecorder struct {
	mock *MockTargetResolver
}

// NewMockTargetResolver creates a new mock instance.
func NewMockTargetResolver(ctrl *gomock.Controller) *MockTargetResolver {
	mock := &MockTargetResolver{ctrl: ctrl}
	mock.recorder = &MockTargetResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetResolver) EXPECT() *MockTargetResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockTargetResolver) Resolve(ctx context.Context, selected project.Project, target project.Target) (project.Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, selected, target)
	ret0, _ := ret[0].(project.Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockTargetResolverMockRecorder) Resolve(ctx, selected, target any) *MockTargetResolverResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockTargetResolver)(nil).Resolve), ctx, selected, target)
	return &MockTargetResolverResolveCall{Call: call}
}

// MockTargetResolverResolveCall wrap *gomock.Call
type MockTargetResolverResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTargetResolverResolveCall) Return(arg0 project.Target, arg1 error) *MockTargetResolverResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTargetResolverResolveCall) Do(f func(context.Context, project.Project, project.Target) (project.Target, error)) *MockTargetResolverResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTargetResolverResolveCall) DoAndReturn(f func(context.Context, project.Project, project.Target) (project.Target, error)) *MockTargetResolverResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProtoLinter is a mock of ProtoLinter interface.
type MockProtoLinter struct {
	ctrl     *gomock.Controller
	recorder *MockProtoLinterMockRecorder
	isgomock struct{}
}

// MockProtoLinterMockRecorder is the mock recorder for MockProtoLinter.
type MockProtoLinterMockRecorder struct {
	mock *MockProtoLinter
}

// NewMockProtoLinter creates a new mock instance.
func NewMockProtoLinter(ctrl *gomock.Controller) *MockProtoLinter {
	mock := &MockProtoLinter{ctrl: ctrl}
	mock.recorder = &MockProtoLinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtoLinter) EXPECT() *MockProtoLinterMockRecorder {
	return m.recorder
}

// Lint mocks base method.
func (m *MockProtoLinter) Lint(ctx context.Context, arg1 project.Project, target project.Target) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lint", ctx, arg1, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lint indicates an expected call of Lint.
func (mr *MockProtoLinterMockRecorder) Lint(ctx, arg1, target any) *MockProtoLinterLintCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lint", reflect.TypeOf((*MockProtoLinter)(nil).Lint), ctx, arg1, target)
	return &MockProtoLinterLintCall{Call: call}
}

// MockProtoLinterLintCall wrap *gomock.Call
type MockProtoLinterLintCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProtoLinterLintCall) Return(arg0 error) *MockProtoLinterLintCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProtoLinterLintCall) Do(f func(context.Context, project.Project, project.Target) error) *MockProtoLinterLintCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProtoLinterLintCall) DoAndReturn(f func(context.Context, project.Project, project.Target) error) *MockProtoLinterLintCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
