// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/internal/service/contractsnapshot (interfaces: Reader)
//
// Generated by this command:
//
//	mockgen -destination mocks/loader.go -package mocks -typed . Reader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	contract "github.com/devctllabs/devctl/internal/domain/contract"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// ReadFile mocks base method.
func (m *MockReader) ReadFile(ctx context.Context, root, name string) (contract.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", ctx, root, name)
	ret0, _ := ret[0].(contract.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockReaderMockRecorder) ReadFile(ctx, root, name any) *MockReaderReadFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockReader)(nil).ReadFile), ctx, root, name)
	return &MockReaderReadFileCall{Call: call}
}

// MockReaderReadFileCall wrap *gomock.Call
type MockReaderReadFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReaderReadFileCall) Return(arg0 contract.File, arg1 error) *MockReaderReadFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReaderReadFileCall) Do(f func(context.Context, string, string) (contract.File, error)) *MockReaderReadFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReaderReadFileCall) DoAndReturn(f func(context.Context, string, string) (contract.File, error)) *MockReaderReadFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadTree mocks base method.
func (m *MockReader) ReadTree(ctx context.Context, root, directory string) ([]contract.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadTree", ctx, root, directory)
	ret0, _ := ret[0].([]contract.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadTree indicates an expected call of ReadTree.
func (mr *MockReaderMockRecorder) ReadTree(ctx, root, directory any) *MockReaderReadTreeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadTree", reflect.TypeOf((*MockReader)(nil).ReadTree), ctx, root, directory)
	return &MockReaderReadTreeCall{Call: call}
}

// MockReaderReadTreeCall wrap *gomock.Call
type MockReaderReadTreeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReaderReadTreeCall) Return(arg0 []contract.File, arg1 error) *MockReaderReadTreeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReaderReadTreeCall) Do(f func(context.Context, string, string) ([]contract.File, error)) *MockReaderReadTreeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReaderReadTreeCall) DoAndReturn(f func(context.Context, string, string) ([]contract.File, error)) *MockReaderReadTreeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
