package main

import (
	"bytes"
	"context"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"

	devctlapp "github.com/devctllabs/devctl/cmd/devctl/internal/app"
	devfs "github.com/devctllabs/go-libs/filesystem"
	docs "github.com/urfave/cli-docs/v3"
)

const referencePath = "docs/user-guide/reference/commands.md"

func main() {
	check := flag.Bool("check", false, "verify that the committed command reference is current")
	flag.Parse()

	content, err := renderReference()
	if err == nil {
		if *check {
			err = checkReference(".", referencePath, content)
		} else {
			err = writeReference(".", referencePath, content)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func renderReference() ([]byte, error) {
	root := devctlapp.New("", "")
	markdown, err := docs.ToTabularMarkdown(root, "devctl")
	if err != nil {
		return nil, fmt.Errorf("generate command reference: %w", err)
	}

	const header = "# Command reference\n\n<!-- Code generated by cmd/devctl/internal/docgen; DO NOT EDIT. Run `mise run docs:generate`. -->\n\n"
	return []byte(header + markdown), nil
}

func checkReference(root, name string, expected []byte) error {
	disk, err := devfs.Open(root)
	if err != nil {
		return fmt.Errorf("filesystem.Open: %w", err)
	}
	actual, readErr := fs.ReadFile(disk, name)
	if readErr != nil {
		readErr = fmt.Errorf("filesystem.ReadFile: %w", readErr)
	}
	closeErr := disk.Close()
	if closeErr != nil {
		closeErr = fmt.Errorf("filesystem.Close: %w", closeErr)
	}
	if err := errors.Join(readErr, closeErr); err != nil {
		return fmt.Errorf("read command reference: %w", err)
	}
	if !bytes.Equal(actual, expected) {
		return errors.New("command reference is out of date; run `mise run docs:generate`")
	}
	return nil
}

func writeReference(root, name string, content []byte) error {
	disk, err := devfs.Open(root)
	if err != nil {
		return fmt.Errorf("filesystem.Open: %w", err)
	}
	_, publishErr := disk.PublishFile(context.Background(), name, devfs.File{
		Content: content,
		Mode:    0o644,
	})
	if publishErr != nil {
		publishErr = fmt.Errorf("filesystem.PublishFile: %w", publishErr)
	}
	closeErr := disk.Close()
	if closeErr != nil {
		closeErr = fmt.Errorf("filesystem.Close: %w", closeErr)
	}
	if err := errors.Join(publishErr, closeErr); err != nil {
		return fmt.Errorf("publish command reference: %w", err)
	}
	return nil
}
