// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/internal/client/generator (interfaces: Adapter)
//
// Generated by this command:
//
//	mockgen -destination mocks/client.go -package mocks -typed . Adapter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	generate "github.com/devctllabs/devctl/internal/domain/generate"
	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockAdapter is a mock of Adapter interface.
type MockAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockAdapterMockRecorder
	isgomock struct{}
}

// MockAdapterMockRecorder is the mock recorder for MockAdapter.
type MockAdapterMockRecorder struct {
	mock *MockAdapter
}

// NewMockAdapter creates a new mock instance.
func NewMockAdapter(ctrl *gomock.Controller) *MockAdapter {
	mock := &MockAdapter{ctrl: ctrl}
	mock.recorder = &MockAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdapter) EXPECT() *MockAdapterMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockAdapter) Generate(ctx context.Context, arg1 project.Project, target project.Target) (generate.Output, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, arg1, target)
	ret0, _ := ret[0].(generate.Output)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockAdapterMockRecorder) Generate(ctx, arg1, target any) *MockAdapterGenerateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockAdapter)(nil).Generate), ctx, arg1, target)
	return &MockAdapterGenerateCall{Call: call}
}

// MockAdapterGenerateCall wrap *gomock.Call
type MockAdapterGenerateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAdapterGenerateCall) Return(arg0 generate.Output, arg1 error) *MockAdapterGenerateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAdapterGenerateCall) Do(f func(context.Context, project.Project, project.Target) (generate.Output, error)) *MockAdapterGenerateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAdapterGenerateCall) DoAndReturn(f func(context.Context, project.Project, project.Target) (generate.Output, error)) *MockAdapterGenerateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
