package oapicodegen_test

import (
	"context"
	"path/filepath"
	"testing"

	oapicodegen "github.com/devctllabs/devctl/internal/client/oapicodegen"
	"github.com/devctllabs/devctl/internal/client/toolrun"
	projectdomain "github.com/devctllabs/devctl/internal/domain/project"
	"github.com/stretchr/testify/require"
)

func TestClientDelegatesOAPIGenerationToRunner(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.test/service\n\ngo 1.26\n\ntool github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen\n")
	writeFixture(t, root, "api/openapi.yaml", "openapi: 3.1.0\ninfo:\n  title: service\n  version: 1.0.0\npaths: {}\n")
	writeFixture(t, root, "tools/oapi/client.yaml", "package: clienthttp\ngenerate:\n  client: true\n")
	var temporary string
	runner := &recordingRunner{run: func(command toolrun.Command) error {
		outputPath := command.Args[5]
		temporary = filepath.Dir(outputPath)
		writeFixture(t, temporary, filepath.Base(outputPath), "// Code generated by oapi-codegen. DO NOT EDIT.\npackage clienthttp\n")
		return nil
	}}
	target := projectdomain.Target{
		ID: "http-client:payments", Family: "http", Input: "api/openapi.yaml",
		Config: "tools/oapi/client.yaml", OutputFile: "client.gen.go",
	}

	output, err := oapicodegen.New(runner).Generate(context.Background(), projectdomain.Project{Root: root}, target)

	require.NoError(t, err)
	require.Equal(t, []toolrun.Command{{
		Name: "go",
		Args: []string{"tool", "oapi-codegen", "--config", "tools/oapi/client.yaml", "-o", filepath.Join(temporary, "client.gen.go"), "api/openapi.yaml"},
		Dir:  root,
	}}, runner.commands)
	require.Equal(t, []byte("// Code generated by oapi-codegen. DO NOT EDIT.\npackage clienthttp\n"), output.Directory.Files[0].Content)
	require.NoDirExists(t, temporary)
}

type recordingRunner struct {
	commands []toolrun.Command
	run      func(toolrun.Command) error
}

func (r *recordingRunner) Run(_ context.Context, command toolrun.Command) error {
	command.Args = append([]string(nil), command.Args...)
	r.commands = append(r.commands, command)
	if r.run != nil {
		return r.run(command)
	}
	return nil
}
