// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/cmd/devctl/internal/sync (interfaces: syncer)
//
// Generated by this command:
//
//	mockgen -destination mocks/sync.go -package mocks -typed . syncer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sync "github.com/devctllabs/devctl/internal/domain/sync"
	gomock "go.uber.org/mock/gomock"
)

// Mocksyncer is a mock of syncer interface.
type Mocksyncer struct {
	ctrl     *gomock.Controller
	recorder *MocksyncerMockRecorder
	isgomock struct{}
}

// MocksyncerMockRecorder is the mock recorder for Mocksyncer.
type MocksyncerMockRecorder struct {
	mock *Mocksyncer
}

// NewMocksyncer creates a new mock instance.
func NewMocksyncer(ctrl *gomock.Controller) *Mocksyncer {
	mock := &Mocksyncer{ctrl: ctrl}
	mock.recorder = &MocksyncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksyncer) EXPECT() *MocksyncerMockRecorder {
	return m.recorder
}

// Sync mocks base method.
func (m *Mocksyncer) Sync(ctx context.Context, command sync.Command) (sync.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, command)
	ret0, _ := ret[0].(sync.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MocksyncerMockRecorder) Sync(ctx, command any) *MocksyncerSyncCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*Mocksyncer)(nil).Sync), ctx, command)
	return &MocksyncerSyncCall{Call: call}
}

// MocksyncerSyncCall wrap *gomock.Call
type MocksyncerSyncCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocksyncerSyncCall) Return(arg0 sync.Result, arg1 error) *MocksyncerSyncCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocksyncerSyncCall) Do(f func(context.Context, sync.Command) (sync.Result, error)) *MocksyncerSyncCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocksyncerSyncCall) DoAndReturn(f func(context.Context, sync.Command) (sync.Result, error)) *MocksyncerSyncCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
