// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/internal/service/project (interfaces: ManifestRepository,ManifestLocator,TargetResolver,ReadinessChecker)
//
// Generated by this command:
//
//	mockgen -destination mocks/service.go -package mocks -typed . ManifestRepository,ManifestLocator,TargetResolver,ReadinessChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockManifestRepository is a mock of ManifestRepository interface.
type MockManifestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockManifestRepositoryMockRecorder
	isgomock struct{}
}

// MockManifestRepositoryMockRecorder is the mock recorder for MockManifestRepository.
type MockManifestRepositoryMockRecorder struct {
	mock *MockManifestRepository
}

// NewMockManifestRepository creates a new mock instance.
func NewMockManifestRepository(ctrl *gomock.Controller) *MockManifestRepository {
	mock := &MockManifestRepository{ctrl: ctrl}
	mock.recorder = &MockManifestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManifestRepository) EXPECT() *MockManifestRepositoryMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockManifestRepository) Load(ctx context.Context, manifestPath string) (project.LoadManifestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, manifestPath)
	ret0, _ := ret[0].(project.LoadManifestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockManifestRepositoryMockRecorder) Load(ctx, manifestPath any) *MockManifestRepositoryLoadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockManifestRepository)(nil).Load), ctx, manifestPath)
	return &MockManifestRepositoryLoadCall{Call: call}
}

// MockManifestRepositoryLoadCall wrap *gomock.Call
type MockManifestRepositoryLoadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestRepositoryLoadCall) Return(arg0 project.LoadManifestResult, arg1 error) *MockManifestRepositoryLoadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestRepositoryLoadCall) Do(f func(context.Context, string) (project.LoadManifestResult, error)) *MockManifestRepositoryLoadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestRepositoryLoadCall) DoAndReturn(f func(context.Context, string) (project.LoadManifestResult, error)) *MockManifestRepositoryLoadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockManifestRepository) Save(ctx context.Context, arg1 project.Project) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockManifestRepositoryMockRecorder) Save(ctx, arg1 any) *MockManifestRepositorySaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockManifestRepository)(nil).Save), ctx, arg1)
	return &MockManifestRepositorySaveCall{Call: call}
}

// MockManifestRepositorySaveCall wrap *gomock.Call
type MockManifestRepositorySaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestRepositorySaveCall) Return(arg0 bool, arg1 error) *MockManifestRepositorySaveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestRepositorySaveCall) Do(f func(context.Context, project.Project) (bool, error)) *MockManifestRepositorySaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestRepositorySaveCall) DoAndReturn(f func(context.Context, project.Project) (bool, error)) *MockManifestRepositorySaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockManifestLocator is a mock of ManifestLocator interface.
type MockManifestLocator struct {
	ctrl     *gomock.Controller
	recorder *MockManifestLocatorMockRecorder
	isgomock struct{}
}

// MockManifestLocatorMockRecorder is the mock recorder for MockManifestLocator.
type MockManifestLocatorMockRecorder struct {
	mock *MockManifestLocator
}

// NewMockManifestLocator creates a new mock instance.
func NewMockManifestLocator(ctrl *gomock.Controller) *MockManifestLocator {
	mock := &MockManifestLocator{ctrl: ctrl}
	mock.recorder = &MockManifestLocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManifestLocator) EXPECT() *MockManifestLocatorMockRecorder {
	return m.recorder
}

// RegularFile mocks base method.
func (m *MockManifestLocator) RegularFile(ctx context.Context, root, relativePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegularFile", ctx, root, relativePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegularFile indicates an expected call of RegularFile.
func (mr *MockManifestLocatorMockRecorder) RegularFile(ctx, root, relativePath any) *MockManifestLocatorRegularFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegularFile", reflect.TypeOf((*MockManifestLocator)(nil).RegularFile), ctx, root, relativePath)
	return &MockManifestLocatorRegularFileCall{Call: call}
}

// MockManifestLocatorRegularFileCall wrap *gomock.Call
type MockManifestLocatorRegularFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestLocatorRegularFileCall) Return(arg0 bool, arg1 error) *MockManifestLocatorRegularFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestLocatorRegularFileCall) Do(f func(context.Context, string, string) (bool, error)) *MockManifestLocatorRegularFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestLocatorRegularFileCall) DoAndReturn(f func(context.Context, string, string) (bool, error)) *MockManifestLocatorRegularFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WorkingDirectory mocks base method.
func (m *MockManifestLocator) WorkingDirectory(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkingDirectory", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkingDirectory indicates an expected call of WorkingDirectory.
func (mr *MockManifestLocatorMockRecorder) WorkingDirectory(ctx any) *MockManifestLocatorWorkingDirectoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkingDirectory", reflect.TypeOf((*MockManifestLocator)(nil).WorkingDirectory), ctx)
	return &MockManifestLocatorWorkingDirectoryCall{Call: call}
}

// MockManifestLocatorWorkingDirectoryCall wrap *gomock.Call
type MockManifestLocatorWorkingDirectoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestLocatorWorkingDirectoryCall) Return(arg0 string, arg1 error) *MockManifestLocatorWorkingDirectoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestLocatorWorkingDirectoryCall) Do(f func(context.Context) (string, error)) *MockManifestLocatorWorkingDirectoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestLocatorWorkingDirectoryCall) DoAndReturn(f func(context.Context) (string, error)) *MockManifestLocatorWorkingDirectoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTargetResolver is a mock of TargetResolver interface.
type MockTargetResolver struct {
	ctrl     *gomock.Controller
	recorder *MockTargetResolverMockRecorder
	isgomock struct{}
}

// MockTargetResolverMockRecorder is the mock recorder for MockTargetResolver.
type MockTargetResolverMockRecorder struct {
	mock *MockTargetResolver
}

// NewMockTargetResolver creates a new mock instance.
func NewMockTargetResolver(ctrl *gomock.Controller) *MockTargetResolver {
	mock := &MockTargetResolver{ctrl: ctrl}
	mock.recorder = &MockTargetResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetResolver) EXPECT() *MockTargetResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockTargetResolver) Resolve(ctx context.Context, selected project.Project, target project.Target) (project.Target, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, selected, target)
	ret0, _ := ret[0].(project.Target)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockTargetResolverMockRecorder) Resolve(ctx, selected, target any) *MockTargetResolverResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockTargetResolver)(nil).Resolve), ctx, selected, target)
	return &MockTargetResolverResolveCall{Call: call}
}

// MockTargetResolverResolveCall wrap *gomock.Call
type MockTargetResolverResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTargetResolverResolveCall) Return(arg0 project.Target, arg1 error) *MockTargetResolverResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTargetResolverResolveCall) Do(f func(context.Context, project.Project, project.Target) (project.Target, error)) *MockTargetResolverResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTargetResolverResolveCall) DoAndReturn(f func(context.Context, project.Project, project.Target) (project.Target, error)) *MockTargetResolverResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockReadinessChecker is a mock of ReadinessChecker interface.
type MockReadinessChecker struct {
	ctrl     *gomock.Controller
	recorder *MockReadinessCheckerMockRecorder
	isgomock struct{}
}

// MockReadinessCheckerMockRecorder is the mock recorder for MockReadinessChecker.
type MockReadinessCheckerMockRecorder struct {
	mock *MockReadinessChecker
}

// NewMockReadinessChecker creates a new mock instance.
func NewMockReadinessChecker(ctrl *gomock.Controller) *MockReadinessChecker {
	mock := &MockReadinessChecker{ctrl: ctrl}
	mock.recorder = &MockReadinessCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadinessChecker) EXPECT() *MockReadinessCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockReadinessChecker) Check(ctx context.Context, selected project.Project) ([]project.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, selected)
	ret0, _ := ret[0].([]project.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockReadinessCheckerMockRecorder) Check(ctx, selected any) *MockReadinessCheckerCheckCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockReadinessChecker)(nil).Check), ctx, selected)
	return &MockReadinessCheckerCheckCall{Call: call}
}

// MockReadinessCheckerCheckCall wrap *gomock.Call
type MockReadinessCheckerCheckCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadinessCheckerCheckCall) Return(arg0 []project.Issue, arg1 error) *MockReadinessCheckerCheckCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadinessCheckerCheckCall) Do(f func(context.Context, project.Project) ([]project.Issue, error)) *MockReadinessCheckerCheckCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadinessCheckerCheckCall) DoAndReturn(f func(context.Context, project.Project) ([]project.Issue, error)) *MockReadinessCheckerCheckCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
