// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/internal/service/projectreadiness (interfaces: Workspace)
//
// Generated by this command:
//
//	mockgen -destination mocks/checker.go -package mocks -typed . Workspace
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkspace is a mock of Workspace interface.
type MockWorkspace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceMockRecorder
	isgomock struct{}
}

// MockWorkspaceMockRecorder is the mock recorder for MockWorkspace.
type MockWorkspaceMockRecorder struct {
	mock *MockWorkspace
}

// NewMockWorkspace creates a new mock instance.
func NewMockWorkspace(ctrl *gomock.Controller) *MockWorkspace {
	mock := &MockWorkspace{ctrl: ctrl}
	mock.recorder = &MockWorkspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspace) EXPECT() *MockWorkspaceMockRecorder {
	return m.recorder
}

// Directory mocks base method.
func (m *MockWorkspace) Directory(ctx context.Context, root, relativePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Directory", ctx, root, relativePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Directory indicates an expected call of Directory.
func (mr *MockWorkspaceMockRecorder) Directory(ctx, root, relativePath any) *MockWorkspaceDirectoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Directory", reflect.TypeOf((*MockWorkspace)(nil).Directory), ctx, root, relativePath)
	return &MockWorkspaceDirectoryCall{Call: call}
}

// MockWorkspaceDirectoryCall wrap *gomock.Call
type MockWorkspaceDirectoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceDirectoryCall) Return(arg0 bool, arg1 error) *MockWorkspaceDirectoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceDirectoryCall) Do(f func(context.Context, string, string) (bool, error)) *MockWorkspaceDirectoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceDirectoryCall) DoAndReturn(f func(context.Context, string, string) (bool, error)) *MockWorkspaceDirectoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadBytes mocks base method.
func (m *MockWorkspace) ReadBytes(ctx context.Context, root, relativePath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBytes", ctx, root, relativePath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBytes indicates an expected call of ReadBytes.
func (mr *MockWorkspaceMockRecorder) ReadBytes(ctx, root, relativePath any) *MockWorkspaceReadBytesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBytes", reflect.TypeOf((*MockWorkspace)(nil).ReadBytes), ctx, root, relativePath)
	return &MockWorkspaceReadBytesCall{Call: call}
}

// MockWorkspaceReadBytesCall wrap *gomock.Call
type MockWorkspaceReadBytesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceReadBytesCall) Return(arg0 []byte, arg1 error) *MockWorkspaceReadBytesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceReadBytesCall) Do(f func(context.Context, string, string) ([]byte, error)) *MockWorkspaceReadBytesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceReadBytesCall) DoAndReturn(f func(context.Context, string, string) ([]byte, error)) *MockWorkspaceReadBytesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RegularFile mocks base method.
func (m *MockWorkspace) RegularFile(ctx context.Context, root, relativePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegularFile", ctx, root, relativePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegularFile indicates an expected call of RegularFile.
func (mr *MockWorkspaceMockRecorder) RegularFile(ctx, root, relativePath any) *MockWorkspaceRegularFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegularFile", reflect.TypeOf((*MockWorkspace)(nil).RegularFile), ctx, root, relativePath)
	return &MockWorkspaceRegularFileCall{Call: call}
}

// MockWorkspaceRegularFileCall wrap *gomock.Call
type MockWorkspaceRegularFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRegularFileCall) Return(arg0 bool, arg1 error) *MockWorkspaceRegularFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRegularFileCall) Do(f func(context.Context, string, string) (bool, error)) *MockWorkspaceRegularFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRegularFileCall) DoAndReturn(f func(context.Context, string, string) (bool, error)) *MockWorkspaceRegularFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
