// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/internal/service/targetinput (interfaces: EntrypointResolver,SnapshotLoader)
//
// Generated by this command:
//
//	mockgen -destination mocks/resolver.go -package mocks -typed . EntrypointResolver,SnapshotLoader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	contract "github.com/devctllabs/devctl/internal/domain/contract"
	gomock "go.uber.org/mock/gomock"
)

// MockEntrypointResolver is a mock of EntrypointResolver interface.
type MockEntrypointResolver struct {
	ctrl     *gomock.Controller
	recorder *MockEntrypointResolverMockRecorder
	isgomock struct{}
}

// MockEntrypointResolverMockRecorder is the mock recorder for MockEntrypointResolver.
type MockEntrypointResolverMockRecorder struct {
	mock *MockEntrypointResolver
}

// NewMockEntrypointResolver creates a new mock instance.
func NewMockEntrypointResolver(ctrl *gomock.Controller) *MockEntrypointResolver {
	mock := &MockEntrypointResolver{ctrl: ctrl}
	mock.recorder = &MockEntrypointResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntrypointResolver) EXPECT() *MockEntrypointResolverMockRecorder {
	return m.recorder
}

// ResolveContract mocks base method.
func (m *MockEntrypointResolver) ResolveContract(ctx context.Context, location contract.Location) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveContract", ctx, location)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveContract indicates an expected call of ResolveContract.
func (mr *MockEntrypointResolverMockRecorder) ResolveContract(ctx, location any) *MockEntrypointResolverResolveContractCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveContract", reflect.TypeOf((*MockEntrypointResolver)(nil).ResolveContract), ctx, location)
	return &MockEntrypointResolverResolveContractCall{Call: call}
}

// MockEntrypointResolverResolveContractCall wrap *gomock.Call
type MockEntrypointResolverResolveContractCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEntrypointResolverResolveContractCall) Return(arg0 string, arg1 error) *MockEntrypointResolverResolveContractCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEntrypointResolverResolveContractCall) Do(f func(context.Context, contract.Location) (string, error)) *MockEntrypointResolverResolveContractCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEntrypointResolverResolveContractCall) DoAndReturn(f func(context.Context, contract.Location) (string, error)) *MockEntrypointResolverResolveContractCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSnapshotLoader is a mock of SnapshotLoader interface.
type MockSnapshotLoader struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotLoaderMockRecorder
	isgomock struct{}
}

// MockSnapshotLoaderMockRecorder is the mock recorder for MockSnapshotLoader.
type MockSnapshotLoaderMockRecorder struct {
	mock *MockSnapshotLoader
}

// NewMockSnapshotLoader creates a new mock instance.
func NewMockSnapshotLoader(ctrl *gomock.Controller) *MockSnapshotLoader {
	mock := &MockSnapshotLoader{ctrl: ctrl}
	mock.recorder = &MockSnapshotLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotLoader) EXPECT() *MockSnapshotLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockSnapshotLoader) Load(ctx context.Context, root, treeRoot string, expected contract.MetadataExpectation) (contract.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, root, treeRoot, expected)
	ret0, _ := ret[0].(contract.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockSnapshotLoaderMockRecorder) Load(ctx, root, treeRoot, expected any) *MockSnapshotLoaderLoadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockSnapshotLoader)(nil).Load), ctx, root, treeRoot, expected)
	return &MockSnapshotLoaderLoadCall{Call: call}
}

// MockSnapshotLoaderLoadCall wrap *gomock.Call
type MockSnapshotLoaderLoadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotLoaderLoadCall) Return(arg0 contract.Snapshot, arg1 error) *MockSnapshotLoaderLoadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotLoaderLoadCall) Do(f func(context.Context, string, string, contract.MetadataExpectation) (contract.Snapshot, error)) *MockSnapshotLoaderLoadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotLoaderLoadCall) DoAndReturn(f func(context.Context, string, string, contract.MetadataExpectation) (contract.Snapshot, error)) *MockSnapshotLoaderLoadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
