// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/devctllabs/devctl/internal/service/sync (interfaces: ProjectRepository,Materializer,WorkspaceRepository)
//
// Generated by this command:
//
//	mockgen -destination mocks/sync_service.go -package mocks -typed . ProjectRepository,Materializer,WorkspaceRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	artifact "github.com/devctllabs/devctl/internal/domain/artifact"
	contract "github.com/devctllabs/devctl/internal/domain/contract"
	project "github.com/devctllabs/devctl/internal/domain/project"
	gomock "go.uber.org/mock/gomock"
)

// MockProjectRepository is a mock of ProjectRepository interface.
type MockProjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProjectRepositoryMockRecorder
	isgomock struct{}
}

// MockProjectRepositoryMockRecorder is the mock recorder for MockProjectRepository.
type MockProjectRepositoryMockRecorder struct {
	mock *MockProjectRepository
}

// NewMockProjectRepository creates a new mock instance.
func NewMockProjectRepository(ctrl *gomock.Controller) *MockProjectRepository {
	mock := &MockProjectRepository{ctrl: ctrl}
	mock.recorder = &MockProjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectRepository) EXPECT() *MockProjectRepositoryMockRecorder {
	return m.recorder
}

// LoadProject mocks base method.
func (m *MockProjectRepository) LoadProject(ctx context.Context, manifestPath string) (project.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadProject", ctx, manifestPath)
	ret0, _ := ret[0].(project.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadProject indicates an expected call of LoadProject.
func (mr *MockProjectRepositoryMockRecorder) LoadProject(ctx, manifestPath any) *MockProjectRepositoryLoadProjectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadProject", reflect.TypeOf((*MockProjectRepository)(nil).LoadProject), ctx, manifestPath)
	return &MockProjectRepositoryLoadProjectCall{Call: call}
}

// MockProjectRepositoryLoadProjectCall wrap *gomock.Call
type MockProjectRepositoryLoadProjectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectRepositoryLoadProjectCall) Return(arg0 project.Project, arg1 error) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectRepositoryLoadProjectCall) Do(f func(context.Context, string) (project.Project, error)) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectRepositoryLoadProjectCall) DoAndReturn(f func(context.Context, string) (project.Project, error)) *MockProjectRepositoryLoadProjectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMaterializer is a mock of Materializer interface.
type MockMaterializer struct {
	ctrl     *gomock.Controller
	recorder *MockMaterializerMockRecorder
	isgomock struct{}
}

// MockMaterializerMockRecorder is the mock recorder for MockMaterializer.
type MockMaterializerMockRecorder struct {
	mock *MockMaterializer
}

// NewMockMaterializer creates a new mock instance.
func NewMockMaterializer(ctrl *gomock.Controller) *MockMaterializer {
	mock := &MockMaterializer{ctrl: ctrl}
	mock.recorder = &MockMaterializerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaterializer) EXPECT() *MockMaterializerMockRecorder {
	return m.recorder
}

// Materialize mocks base method.
func (m *MockMaterializer) Materialize(ctx context.Context, root string, source project.Source, reference contract.Reference) (contract.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Materialize", ctx, root, source, reference)
	ret0, _ := ret[0].(contract.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Materialize indicates an expected call of Materialize.
func (mr *MockMaterializerMockRecorder) Materialize(ctx, root, source, reference any) *MockMaterializerMaterializeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Materialize", reflect.TypeOf((*MockMaterializer)(nil).Materialize), ctx, root, source, reference)
	return &MockMaterializerMaterializeCall{Call: call}
}

// MockMaterializerMaterializeCall wrap *gomock.Call
type MockMaterializerMaterializeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMaterializerMaterializeCall) Return(arg0 contract.Snapshot, arg1 error) *MockMaterializerMaterializeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMaterializerMaterializeCall) Do(f func(context.Context, string, project.Source, contract.Reference) (contract.Snapshot, error)) *MockMaterializerMaterializeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMaterializerMaterializeCall) DoAndReturn(f func(context.Context, string, project.Source, contract.Reference) (contract.Snapshot, error)) *MockMaterializerMaterializeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockWorkspaceRepository is a mock of WorkspaceRepository interface.
type MockWorkspaceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkspaceRepositoryMockRecorder is the mock recorder for MockWorkspaceRepository.
type MockWorkspaceRepositoryMockRecorder struct {
	mock *MockWorkspaceRepository
}

// NewMockWorkspaceRepository creates a new mock instance.
func NewMockWorkspaceRepository(ctrl *gomock.Controller) *MockWorkspaceRepository {
	mock := &MockWorkspaceRepository{ctrl: ctrl}
	mock.recorder = &MockWorkspaceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspaceRepository) EXPECT() *MockWorkspaceRepositoryMockRecorder {
	return m.recorder
}

// PreviewPruneDirectories mocks base method.
func (m *MockWorkspaceRepository) PreviewPruneDirectories(ctx context.Context, root, parent string, keep []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewPruneDirectories", ctx, root, parent, keep)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewPruneDirectories indicates an expected call of PreviewPruneDirectories.
func (mr *MockWorkspaceRepositoryMockRecorder) PreviewPruneDirectories(ctx, root, parent, keep any) *MockWorkspaceRepositoryPreviewPruneDirectoriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewPruneDirectories", reflect.TypeOf((*MockWorkspaceRepository)(nil).PreviewPruneDirectories), ctx, root, parent, keep)
	return &MockWorkspaceRepositoryPreviewPruneDirectoriesCall{Call: call}
}

// MockWorkspaceRepositoryPreviewPruneDirectoriesCall wrap *gomock.Call
type MockWorkspaceRepositoryPreviewPruneDirectoriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRepositoryPreviewPruneDirectoriesCall) Return(arg0 []string, arg1 error) *MockWorkspaceRepositoryPreviewPruneDirectoriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRepositoryPreviewPruneDirectoriesCall) Do(f func(context.Context, string, string, []string) ([]string, error)) *MockWorkspaceRepositoryPreviewPruneDirectoriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRepositoryPreviewPruneDirectoriesCall) DoAndReturn(f func(context.Context, string, string, []string) ([]string, error)) *MockWorkspaceRepositoryPreviewPruneDirectoriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PruneDirectories mocks base method.
func (m *MockWorkspaceRepository) PruneDirectories(ctx context.Context, root, parent string, keep []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneDirectories", ctx, root, parent, keep)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PruneDirectories indicates an expected call of PruneDirectories.
func (mr *MockWorkspaceRepositoryMockRecorder) PruneDirectories(ctx, root, parent, keep any) *MockWorkspaceRepositoryPruneDirectoriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneDirectories", reflect.TypeOf((*MockWorkspaceRepository)(nil).PruneDirectories), ctx, root, parent, keep)
	return &MockWorkspaceRepositoryPruneDirectoriesCall{Call: call}
}

// MockWorkspaceRepositoryPruneDirectoriesCall wrap *gomock.Call
type MockWorkspaceRepositoryPruneDirectoriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRepositoryPruneDirectoriesCall) Return(arg0 []string, arg1 error) *MockWorkspaceRepositoryPruneDirectoriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRepositoryPruneDirectoriesCall) Do(f func(context.Context, string, string, []string) ([]string, error)) *MockWorkspaceRepositoryPruneDirectoriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRepositoryPruneDirectoriesCall) DoAndReturn(f func(context.Context, string, string, []string) ([]string, error)) *MockWorkspaceRepositoryPruneDirectoriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PublishDirectory mocks base method.
func (m *MockWorkspaceRepository) PublishDirectory(ctx context.Context, root, target string, tree artifact.Tree) (artifact.PublishResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDirectory", ctx, root, target, tree)
	ret0, _ := ret[0].(artifact.PublishResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishDirectory indicates an expected call of PublishDirectory.
func (mr *MockWorkspaceRepositoryMockRecorder) PublishDirectory(ctx, root, target, tree any) *MockWorkspaceRepositoryPublishDirectoryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDirectory", reflect.TypeOf((*MockWorkspaceRepository)(nil).PublishDirectory), ctx, root, target, tree)
	return &MockWorkspaceRepositoryPublishDirectoryCall{Call: call}
}

// MockWorkspaceRepositoryPublishDirectoryCall wrap *gomock.Call
type MockWorkspaceRepositoryPublishDirectoryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRepositoryPublishDirectoryCall) Return(arg0 artifact.PublishResult, arg1 error) *MockWorkspaceRepositoryPublishDirectoryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRepositoryPublishDirectoryCall) Do(f func(context.Context, string, string, artifact.Tree) (artifact.PublishResult, error)) *MockWorkspaceRepositoryPublishDirectoryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRepositoryPublishDirectoryCall) DoAndReturn(f func(context.Context, string, string, artifact.Tree) (artifact.PublishResult, error)) *MockWorkspaceRepositoryPublishDirectoryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PublishFile mocks base method.
func (m *MockWorkspaceRepository) PublishFile(ctx context.Context, root, target string, content []byte) (artifact.PublishResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishFile", ctx, root, target, content)
	ret0, _ := ret[0].(artifact.PublishResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishFile indicates an expected call of PublishFile.
func (mr *MockWorkspaceRepositoryMockRecorder) PublishFile(ctx, root, target, content any) *MockWorkspaceRepositoryPublishFileCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishFile", reflect.TypeOf((*MockWorkspaceRepository)(nil).PublishFile), ctx, root, target, content)
	return &MockWorkspaceRepositoryPublishFileCall{Call: call}
}

// MockWorkspaceRepositoryPublishFileCall wrap *gomock.Call
type MockWorkspaceRepositoryPublishFileCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkspaceRepositoryPublishFileCall) Return(arg0 artifact.PublishResult, arg1 error) *MockWorkspaceRepositoryPublishFileCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkspaceRepositoryPublishFileCall) Do(f func(context.Context, string, string, []byte) (artifact.PublishResult, error)) *MockWorkspaceRepositoryPublishFileCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkspaceRepositoryPublishFileCall) DoAndReturn(f func(context.Context, string, string, []byte) (artifact.PublishResult, error)) *MockWorkspaceRepositoryPublishFileCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
